### ISSUE TITLE
Custom Properties

### ISSUE THREAD

**Issue by rawdlite** [sommalia/moco-wrapper#3]
Hi,

Appreciate your work on moco-wrapper.
I am missing the possibility to write custom properties though.
Any thoughts on that?

cheers
tom

**Comment by sommalia** [comment]
Hello,

thank your for using the moco-wrapper. 

Currently custom properties can not be created over the api. You would have to create them via the webapp (should be under https://{subdomain}.mocoapp.com/settings/custom_properties) first.

Once you have created them you can use them as a parameter (as shown here: https://moco-wrapper.readthedocs.io/en/latest/code_overview/models/company.html#moco_wrapper.models.Company.create).

Regards,
sommalia

**Comment by rawdlite** [comment]
Thank you for replying.
I obviously overlooked the custom properties parameter in project, user and company.
Yet i am missing them in Endpoints:
- Contact
- Deal
- Offer
- Invoice

I forked and adding the missing parameter to these endpoints was quite straightforward.
I can do a pull request if you want me to.

Cheers,
tom

**Comment by sommalia** [comment]
Thank you for your work. A pull request would be very much appreciated. 

Regards,
sommalia
