### ISSUE TITLE
missing parameter labels in Deal 

### ISSUE THREAD

**Issue by rawdlite** [sommalia/moco-wrapper#6]
* moco-wrapper version: 0.11.0
* Python version: 3.9.8
* Operating System: Linux / Mac OSX

### Description

Describe what you were trying to get done.

Create a Label for a Deal via API

Tell us what happened, what went wrong, and what you expected to happen.

Expected to be able to set a label like with company or project.
Yet there is no parameter for labels in the deal model.

Would be great if this could be added.

cheers tom

**Comment by sommalia** [comment]
Hello Tom,

thank you for bringing this issue to our attention.

Unfortunatly the official documentation does not mention a tags/labels paramater for the deals-entity (at least for updating/creating) (https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/deals.md). 

However it could be possible to set the tags regardless. Could you try to that and get back to us?

A corresponding curl request would look something like this:

````
curl -X POST \
  'https://{domain}.mocoapp.com/api/v1/deals' \
  -H 'Authorization: Token token=YOUR_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{
        "name": "Beispiel AG Website Relaunch",
        "currency": "EUR",
        "money": "25000",
        "reminder_date": "2018-12-01",
        "user_id": 123,
        "deal_category_id": 456,
        "tags": ["testlabel"]
      }'
````


If you succeed feel free to add the tags parameter in a pull request.

If that does not work please create an issue with the main developer of the api over at https://github.com/hundertzehn/mocoapp-api-docs/issues

Regards
sommalia

**Comment by rawdlite** [comment]
Thank you for your prompt response.
Could create a deal with a curl request as proposed, alas the the label was not created.
So i will create an issue with the moco-api repository then.
You want a cross link?

Cheers tom

**Comment by sommalia** [comment]
Hello Tom. Feel free to cross link to this issue.

**Comment by rawdlite** [comment]
Issue at mocoapp-api-docs is https://github.com/hundertzehn/mocoapp-api-docs/issues/156
