### ISSUE TITLE
Company.delete missing

### ISSUE THREAD

**Issue by derfabianpeter** [sommalia/moco-wrapper#9]
* moco-wrapper version: latest
* Python version: 3.10.x
* Operating System: Linux

### Description

Trying to DELETE a Company but that is apparently not implemented. Is there any workaround for deleting companies through the lib or do I have to implement this on my own?

**Comment by derfabianpeter** [comment]
Thanks, that would be great!

**Comment by sommalia** [comment]
Hello Fabian,

please try again with the new version 0.11.2.

Regards,
sommalia
